version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "main"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/.github/workflows"
    target-branch: "main"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/docs"
    target-branch: "main"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/"
    target-branch: "main"
    schedule:
      interval: weekly
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
